web1/urls.py
from django.urls import path
from . import views

app_name='web1'
urlpatterns=[
        path('',views.manage_order,name='manage_order'),
        path('<str:order_number>/',views.order_detail,name='order_detail'),
]

website/urls.py
from django.contrib import admin
from django.urls import include,path
from web1 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.manage_order),
    path('order/',include('web1.urls')),
    path('add_order/',views.add_order),
    path('submit_order/<str:order_number>/',views.submit_order),
    path('edit_order/<str:order_number>/',views.edit_order),
    path('container/<str:container_number>/',views.container_detail),
]

web1/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Order(models.Model):
    order_number=models.CharField(max_length=200)
    customer_code=models.CharField(max_length=200)
    order_date=models.DateTimeField('date ordered')
    assign_date=models.DateTimeField('date assigned')
    survey_locations=models.CharField(max_length=200)
    depot_code=models.CharField(max_length=200)
    depot_name=models.CharField(max_length=200)
    unit_type=models.CharField(max_length=200)
    qty=models.IntegerField()
    release_number=models.CharField(max_length=200,default='0')
    survey_code=models.CharField(max_length=200)
    remark=models.TextField()

    def __str__(self):
        return self.order_number

class Container(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE)
    container_number=models.CharField(max_length=200)
    content=models.TextField()

    def __str__(self):
        return self.container_number

web1/views.py
from django.shortcuts import render
from django.http import HttpResponse
from web1.models import Order,Container
from django.template.loader import get_template
from django.utils import timezone
import re

# Create your views here.

def manage_order(request):
    orders=Order.objects.all()
    return render(request,'web1/index.html',locals())

def order_detail(request,order_number):
    order=Order.objects.get(order_number=order_number)
    containers=order.container_set.all()
    return render(request,'web1/order.html',locals())

def add_order(request):
    new_order_number=''.join(re.split('[\s\-\+\.:]',str(timezone.now()))[0:7])
    return render(request,'web1/new_order.html',locals())

def submit_order(request,order_number):
    new_order=Order()
    new_order.order_number=order_number
    new_order.customer_code=request.POST['customer_code']
    new_order.order_date=request.POST['order_date']
    new_order.assign_date=request.POST['assign_date']
    new_order.survey_locations=request.POST['survey_locations']
    new_order.depot_code=request.POST['depot_code']
    new_order.depot_name=request.POST['depot_name']
    new_order.unit_type=request.POST['unit_type']
    new_order.qty=request.POST['qty']
    new_order.release_number=request.POST['release_number']
    new_order.survey_code=request.POST['survey_code']
    new_order.remark=request.POST['remark']
    new_order.save()
    for i in range(int(request.POST['container_count'])):
        new_order.container_set.create(container_number=request.POST['container%s'%i],content=request.POST['container%s_content'%i])
    new_order.save()
    orders=Order.objects.all()
    return render(request,'web1/index.html',locals())

def edit_order(request,order_number):
    order=Order.objects.get(order_number=order_number)
    order.customer_code=request.POST['customer_code']
    order.survey_locations=request.POST['survey_locations']
    order.depot_code=request.POST['depot_code']
    order.depot_name=request.POST['depot_name']
    order.unit_type=request.POST['unit_type']
    order.release_number=request.POST['release_number']
    order.survey_code=request.POST['survey_code']
    order.remark=request.POST['remark']
    order.save()
    return render(request,'web1/order.html',locals())

def container_detail(request,container_number):
    container=Container.objects.get(container_number=container_number)
    order=container.order
    containers=order.container_set.all()
    return render(request,'web1/container.html',locals())

web1/templates/web1/base.html
<!-- base.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>
        {% block title%} {% endblock %}
    </title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.staticfile.org/angular.js/1.4.6/angular.min.js"></script>

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <div class='container-fluid'>
        {% include 'web1/header.html'%}
        <div class='col-sm-6 col-md-6' style='background:#ffffff;border-top-right-radius:4px; border-top-left-radius:4px; border-bottom-left-radius:4px; border-bottom-right-radius:4px;border:1px solid  #d6dad4;'>
            <div class='panel panel-default' style='background:#70c048;border-top-right-radius:10px; border-top-left-radius:10px;border-bottom-left-radius:10px; border-bottom-right-radius:10px;margin-left:4px;margin-top:17px;margin-right:3px;'>
                <div class='panel-heading' style='background:#70c048;text-align:left;border-top-right-radius:10px; border-top-left-radius:10px;border-bottom:#70c048'>
                    {% block headmmessage %}{% endblock %}
                </div>
                <div class='panel body' style='text-align:left;margin-left:15px;margin-right:15px;'>
                    {% block content %} {% endblock %}
                </div>
                <div class='panel-footer' >
                    {% include 'web1/footer.html' %}
                </div>
            </div>
        </div>
	<div class='col-sm-6 col-md-6' style='background:#ffffff;border-top-right-radius:4px; border-top-left-radius:4px; border-bottom-left-radius:4px; border-bottom-right-radius:4px;border:1px solid  #d6dad4;'>
            <div class='panel panel-default' style='background:#70c048;border-top-right-radius:10px; border-top-left-radius:10px;border-bottom-left-radius:10px; border-bottom-right-radius:10px;margin-left:4px;margin-top:17px;margin-right:3px;'>
                <div class='panel-heading' style='background:#70c048;text-align:left;border-top-right-radius:10px; border-top-left-radius:10px;border-bottom:#70c048'>
                    {% block container-message %}{% endblock %}
                </div>
                <div class='panel body' style='text-align:left;margin-left:15px;margin-right:15px;' id='container_content'>
                    {% block container-content %} {% endblock %}
                </div>
                <div class='panel-footer' >
                    {% include 'web1/footer.html' %}
                </div>
            </div>
        </div>
    </div>
</body>
</html>

web1/templates/web1/container.html
<!-- order.html -->
{% extends 'web1/base.html' %}
{% block title %}{{order.order_number}}{% endblock%}
{% block headmmessage %}
<h3 id='order_number' style='font-family:微软雅黑;'>{{order.order_number}}</h3>
<button type='button' onclick='edit_order()' id='order_edit_button' style="border-top-right-radius:5px; border-top-left-radius:5px; border-bottom-left-radius:5px; border-bottom-right-radius:5px;" >Edit</button>
{% endblock %}
{% block content %}
<table id='order_content' class='table table-bordered table-striped'>
{% csrf_token %}
    <tr><td>Order Number</td><td>{{order.order_number}}</td></tr>
    <tr><td>Customer Code</td><td>{{order.customer_code}}</td></tr>
    <tr><td>Order Date</td><td>{{order.order_date}}</td></tr>
    <tr><td>Assign Date</td><td>{{order.assign_date}}</td></tr>
    <tr><td>Survey Locations</td><td>{{order.survey_locations}}</td></tr>
    <tr><td>Depot Code</td><td>{{order.depot_code}}</td></tr>
    <tr><td>Depot Name</td><td>{{order.depot_name}}</td></tr>
    <tr><td>Unit Type</td><td>{{order.unit_type}}</td></tr>
    <tr><td>Qty</td><td>{{order.qty}}</td></tr>
    <tr><td>Release Number</td><td>{{order.release_number}}</td></tr>
    <tr><td>Survey Code</td><td>{{order.survey_code}}</td></tr>
    <tr><td>Container Numbers</td><td><ul>{% for container in containers %}<li><a href='/container/{{container.container_number}}/'>{{container.container_number}}</li>{% endfor %}</ul></td></tr>
    <tr><td>Remark</td><td>{{order.remark}}</td></tr>
</table>
<script>
    function edit_order(){
        order_table=document.getElementById('order_content');
	order_info=order_table.children[1];
	const_attrs=['order_number','order_date','assign_date','qty','container_numbers'];
	for(var i=0;i<order_info.childElementCount;i++){
            tname=order_info.children[i].children[0].innerHTML.toLowerCase().replace(' ','_');
	    if(const_attrs.includes(tname)){
		continue;
	    }
	    ihtml=order_info.children[i].children[1].innerHTML;
	    order_info.children[i].children[1].innerHTML=`<input type='text' name=${tname} value=${ihtml} style="width:300px;text-align:left;">`;
	}
	button=document.getElementById('order_edit_button');
	button.disabled='true';
	button.style.color='#d6dad4';
	previous_parent=order_table.parentElement;
	order_edit_form=document.createElement('form');
	order_number=document.getElementById('order_number').innerHTML;
	order_edit_form.action='/edit_order/'+order_number+'/';
	order_edit_form.method='post';
	order_edit_form.onsubmit='return checkForm()';
	order_edit_form.appendChild(order_table);
	previous_parent.appendChild(order_edit_form);
	button=document.createElement('button');
	button.type='submit';
	button.innerHTML='Submit';
	order_edit_form.appendChild(button);
}
</script>
<script>
	function checkForm(){
	    return true;
	}
</script>
{% endblock %}
{% block container-message %}
<h3 id='container_number' style='font-family:微软雅黑;'>Container#{{container.container_number}}</h3>
{% endblock %}
{% block container-content %}
<p>{{container.content}}</p>
{% endblock %}

web1/templates/web1/footer.html
<!-- footer.html -->
{% if now %}
<p style='font-family:微软雅黑;'>现在时刻：{{now}}</p>
{% endif %}

web1/templates/web1/header.html
<!-- header.html -->
{% load staticfiles %}
<div class='well' style="text-align:center;background:#ffffff">
    <img src='{% static "images/logo.jpg" %}' height="200" width="300">
    <br/>
    <br/>
    <br/>
    <br/>
    <ul class="nav nav-tabs" style='background: #70c048 ;border-top-right-radius:10px; border-top-left-radius:10px; border-bottom-left-radius:10px; border-bottom-right-radius:10px;'>
        <li><a href="/" style="border-top-right-radius:10px; border-top-left-radius:10px; border-bottom-left-radius:10px; border-bottom-right-radius:10px;width:250px;font-size:30px;">Home</a></li>
	<li><a href="/add_order/" style="border-top-right-radius:10px; border-top-left-radius:10px; border-bottom-left-radius:10px; border-bottom-right-radius:10px;width:250px;font-size:30px;">New Order</a></li>
        <li><a href="/" style="border-top-right-radius:10px; border-top-left-radius:10px; border-bottom-left-radius:10px; border-bottom-right-radius:10px;width:250px;font-size:30px;">Upload</a></li>
        <li><a href="/" style="border-top-right-radius:10px; border-top-left-radius:10px; border-bottom-left-radius:10px; border-bottom-right-radius:10px;width:250px;font-size:30px;">TBD</a></li>
        <li><a href="/" style="border-top-right-radius:10px; border-top-left-radius:10px; border-bottom-left-radius:10px; border-bottom-right-radius:10px;width:250px;font-size:30px;">TBD</a></li>
    </ul>
</div>

web1/templates/web1/index.html
<!-- index.html -->
{% extends 'web1/base.html' %}
{% block title %}Order Manager{% endblock %}
{% block headmmessage %}
    <h3 id='container_info' style='font-family:微软雅黑;'>Order List</h3>
    <script type="text/javascript"> 
    <!-- 
    function MM_jumpMenu(targ,selObj,restore){ //v3.0 
    eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'"); 
    if (restore) selObj.selectedIndex=0; 
    } 
    //--> 
    </script>
{% endblock %}
{% block content %}
    <table class='table table-hover'>
	<th>Order Number</th><th>Customer Code</th><th>Order Date</th>
        {% for order in orders %}
	    <tr><td><a href="{% url 'web1:order_detail' order.order_number %}">{{order.order_number}}</a></td><td>{{order.customer_code}}</td><td>{{order.order_date}}</td></tr>
        {% endfor %}
    </table>
{% endblock %}
{% block container-message %}
<h3 id='container_info' style='font-family:微软雅黑;'>Container</h3>
{% endblock %}
{% block container-content %}
{% endblock %}

web1/templates/web1/new_order.html
<!-- new_order.html -->
{% extends 'web1/base.html' %}
{% block title %}New Order{% endblock%}
{% block headmmessage %}
<!-- <h3 style='font-family:微软雅黑;'></h3> -->
<a style='font-family:微软雅黑;' href='/'><button class='btn' type="button" style='margin-left:6px;' onclick='add_row()'><i class="fa fa-trash"> Cancel</i></button></a>
{% endblock %}
{% block content %}
<form id='submit_order' action='/submit_order/{{new_order_number}}/' method='post' onsubmit='return submit_order_form()'>
{% csrf_token %}	I
    <table class='table table-bordered table-striped'>
	<tr><td style='text-align:center;'>Order Number</td><td>{{new_order_number}}</td></tr>
        <tr><td style='text-align:center;'>Customer Code</td><td><input type='text' name='customer_code' style="width:300px;text-align:left;" autocomplete='off'></td></tr>
	<tr><td style='text-align:center;'>Order Date</td><td><input type='date' name='order_date' style="width:300px;text-align:left;"></td></td></tr>
        <tr><td style='text-align:center;'>Assign Date</td><td><input type='date' name='assign_date' style="width:300px;text-align:left;"></td></tr>
	<tr><td style='text-align:center;'>Survey Locations</td><td><input type='text' name='survey_locations' style="width:300px;text-align:left;" autocomplete='off'></td></tr>
        <tr><td style='text-align:center;'>Depot Code</td><td><input type='text' name='depot_code' style="width:300px;text-align:left;" autocomplete='off'></td></tr>
        <tr><td style='text-align:center;'>Depot Name</td><td><input type='text' name='depot_name' style="width:300px;text-align:left;" autocomplete='off'></td></tr>
        <tr><td style='text-align:center;'>Unit Type</td><td><input type='text' name='unit_type' style="width:300px;text-align:left;"></td></tr>
        <tr><td style='text-align:center;'>Qty</td><td><input type='text' name='qty' style="width:300px;text-align:left;" autocomplete='off'></td></tr>
        <tr><td style='text-align:center;'>Release Number</td><td><input type='text' name='release_number' style="width:300px;text-align:left;" autocomplete='off'></td></tr>
        <tr><td style='text-align:center;'>Survey Code</td><td><input type='text' name='survey_code' style="width:300px;text-align:left;" autocomplete='off'></td></tr>
	<tr><td style='text-align:center;'>Container Number</td><td id='container_numbers'><button class='btn' id='container_add_button' type="button" style='margin-left:6px;' onclick='add_row()'><i class="fa fa-plus"></i></button></td><td id='container_contents'></td></tr>
	<tr><td style='text-align:center;'>Remark</td><td><input type='text' name='remark' style="width:300px;text-align:left;"></td></tr>
    </table>
    <input type='hidden' id='container_count' name='container_count' value=0>
    <button type='submit' style="height:40px;width:100px;border-top-right-radius:3px; border-top-left-radius:3px; border-bottom-left-radius:3px; border-bottom-right-radius:3px;margin-left:10px;margin-bottom:10px;background-color:#70c048;">Submit</button>
    <br/>
</form>
<script>
    function add_row(){
	button=document.getElementById('container_add_button');
	button.disabled='true';
        containers=document.getElementById('container_numbers');
        count_node=document.getElementById('container_count');
        add_icon=containers.lastChild;
        current_container_count=(containers.childElementCount-1)/2;
        containers.insertBefore(document.createElement('br'),add_icon);
        new_input=document.createElement('input');
        new_input.type='text';
        new_input.name='container'+current_container_count;
	new_input.id=new_input.name;
        new_input.autocomplete='off';
        new_input.style="width:300px;text-align:left;margin-top:3px;";
        tmp=Number(count_node.value);
        containers.insertBefore(new_input,add_icon);
        count_node.setAttribute('value',tmp+1);
	button=document.createElement('button');
	button.type='button';
	button.id='save_content_button';
	button.setAttribute('onclick','save_container()');
	button.innerHTML='Save';
	document.getElementById('container_content').appendChild(button);
	new_content=document.createElement('textarea');
	new_content.name=new_input.name+'_content';
	new_content.id='modifying_content';
	new_content.style='border-top-right-radius:3px; border-top-left-radius:3px; border-bottom-left-radius:3px; border-bottom-right-radius:3px;resize:vertical;width:100%;height:500px;';
	document.getElementById('container_content').appendChild(new_content);
    }
</script>
<script>
    function save_container(){
	content=document.getElementById('modifying_content');
	saved_content=document.createElement('input');
	saved_content.type='hidden';
	saved_content.name=content.name;
	saved_content.value=content.value;
	contents_node=document.getElementById('container_contents');
	contents_node.appendChild(saved_content);
	content.remove();
	document.getElementById('save_content_button').remove();
	button=document.getElementById('container_add_button');
        button.removeAttribute('disabled');
    }
</script>
<script>
    function submit_order_form(){
        return true;
    }
</script>

{% endblock %}
{% block container-message %}
<h3 id='container_info' style='font-family:微软雅黑;'>Container</h3>
{% endblock %}
{% block container-content %}
{% endblock %}

web1/templates/web1/order.html
<!-- order.html -->
{% extends 'web1/base.html' %}
{% block title %}{{order.order_number}}{% endblock%}
{% block headmmessage %}
<h3 id='order_number' style='font-family:微软雅黑;'>{{order.order_number}}</h3>
<button type='button' onclick='edit_order()' id='order_edit_button' style="border-top-right-radius:5px; border-top-left-radius:5px; border-bottom-left-radius:5px; border-bottom-right-radius:5px;" >Edit</button>
{% endblock %}
{% block content %}
{% csrf_token %}
<table id='order_content' class='table table-bordered table-striped'>
    <tr><td>Order Number</td><td>{{order.order_number}}</td></tr>
    <tr><td>Customer Code</td><td>{{order.customer_code}}</td></tr>
    <tr><td>Order Date</td><td>{{order.order_date}}</td></tr>
    <tr><td>Assign Date</td><td>{{order.assign_date}}</td></tr>
    <tr><td>Survey Locations</td><td>{{order.survey_locations}}</td></tr>
    <tr><td>Depot Code</td><td>{{order.depot_code}}</td></tr>
    <tr><td>Depot Name</td><td>{{order.depot_name}}</td></tr>
    <tr><td>Unit Type</td><td>{{order.unit_type}}</td></tr>
    <tr><td>Qty</td><td>{{order.qty}}</td></tr>
    <tr><td>Release Number</td><td>{{order.release_number}}</td></tr>
    <tr><td>Survey Code</td><td>{{order.survey_code}}</td></tr>
    <tr><td>Remark</td><td>{{order.remark}}</td></tr>
</table>
<script>
    function edit_order(){
        order_table=document.getElementById('order_content');
	order_info=order_table.children[0];
	const_attrs=['order_number','order_date','assign_date','qty'];
	for(var i=0;i<order_info.childElementCount;i++){
            tname=order_info.children[i].children[0].innerHTML.toLowerCase().replace(' ','_');
	    if(const_attrs.includes(tname)){
		continue;
	    }
            ihtml=order_info.children[i].children[1].innerHTML;
	    order_info.children[i].children[1].innerHTML=`<input type='text' name=${tname} value=${ihtml} style="width:300px;text-align:left;">`;
	}
	button=document.getElementById('order_edit_button');
	button.disabled='true';
	previous_parent=order_table.parentElement;
	order_edit_form=document.createElement('form');
	order_number=document.getElementById('order_number').innerHTML;
	order_edit_form.action='/edit_order/'+order_number+'/';
	order_edit_form.method='post';
	order_edit_form.onsubmit='return checkForm()';
	order_edit_form.appendChild(order_table);
	previous_parent.appendChild(order_edit_form);
	button=document.createElement('button');
	button.type='submit';
	button.innerHTML='Submit';
	order_edit_form.appendChild(button);
}
</script>
<script>
	function checkForm(){
	    return true;
	}
</script>
{% endblock %}